TMPL = {
	auth : [
		"<div class='auth'>",
			"<div class='login-form'>",
				"<div class='title'> Login </div>",
				"<div class='user'>",
					"user <input type='text'>",
				"</div>",
				"<div class='pass1'>",
					"pass <input type='password'>",
				"</div>",
				"<button class='login'> Login </button>",
			"</div>",
			"<div class='reg-form'>",
				"<div class='title'> Registration </div>",
				"<div class='user'>",
					"user <input type='text'>",
				"</div>",
				"<div class='pass1'>",
					"pass1 <input type='password'>",
				"</div>",
				"<div class='pass2'>",
					"pass2 <input type='password'>",
				"</div>",
				"<button class='reg'> Reg </button>",
			"</div>",
		"</div>"].join(''),
		
	mainContainer : [
		"<div class='header'>",
			"<div class='head-title'> Hello,  ${user} ! </div>",
			"<button class='add-bookmark'>add</button>",
			"<button class='statistics'>statistics</button>",
		"</div>",
		"<div class='body'>",
			"<div class='bookmark-list'>",
			"</div>",
		"</div>",
		"<div class='footer'>",
		"</div>"].join(''),
		
	bookmarkItem : [
		"<div class='item'>",
			"<div class='link'><a href='${link}' target='_blank'> Link </a></div>",
			"<div class='name'>${name}</div>",
			"<div class='desc'>${desc}</div>",
			"<div class='buttons'>",
				"<button class='del'>del</button>",
				"<button class='edit'>edit</button>",
			"</button>",
		"</div>"].join(''),
		
	bookmarkAddOrEdit : [
		"<div class='bookmark-add'>",
			"<div class='wrapper'>",
				"<div class='title'> ... </div>",
				"<input class='name'>",
				"<textarea class='desc'></textarea>",
				"<input class='link'>",
				"<div class='buttons'>",
					"<button class='save'>save</button>",
					"<button class='cancel'>cancel</button>",
				"</div>",
			"</div>",
			"<div class='cover'></div>",
		"</div>"].join(''),
		
	dialogWindow :[
		"<div class='dialog-window'>",
			"<div class='wrapper'>",
				"<div class='title'></div>",
				"<div class='text'></div>",
				"<div class='buttons'></div>",
			"</div>",
			"<div class='cover'></div>",
		"</div>",
	].join(''),
	
	stat : [
		"<div class='stat'>",
			"<div class='wrapper'>",
				"<button class='close'>Close</button>",
			"</div>",
			"<div class='cover'></div>",
		"</div>"].join('')
};